# python main_molecules_graph_regression.py --config 'ZINC_LapPE_Hyperboloid_HGCN.json' 
# python main_molecules_graph_regression.py --config 'ZINC_LapPE_Hyperboloid_HNN.json'
# python main_molecules_graph_regression.py --config 'ZINC_LapPE_PoincareBall_HGCN.json'
# python main_molecules_graph_regression.py --config 'ZINC_LapPE_PoincareBall_HNN.json' 

python main_molecules_graph_regression.py --config 'ZINC_RWPE_Hyperboloid_HGCN.json'
python main_molecules_graph_regression.py --config 'ZINC_RWPE_Hyperboloid_HGCN.json'
python main_molecules_graph_regression.py --config 'ZINC_RWPE_Hyperboloid_HGCN.json'
python main_molecules_graph_regression.py --config 'ZINC_RWPE_Hyperboloid_HGCN.json'
# python main_molecules_graph_regression.py --config 'ZINC_RWPE_Hyperboloid_HNN.json'
# python main_molecules_graph_regression.py --config 'ZINC_RWPE_PoincareBall_HGCN.json'
# python main_molecules_graph_regression.py --config 'ZINC_RWPE_PoincareBall_HNN.json'